language: ruby
before_install: 'gem update bundler'
install: 'bundle install --jobs=3 --retry=3' # Suppress the --deployment flag'
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
notifications:
  irc: "irc.freenode.org#jeweler"
