development:
  # Mysql Settings
  adapter: mysql
  encoding: utf8
  database: pro_jobs_development
  username: root
  password:
  pool: 5
  
test: &TEST
  # Mysql Settings
  adapter: mysql
  encoding: utf8
  database: pro_jobs_test
  username: root
  password:
  pool: 5
  
staging:
  # Mysql Settings
  adapter: mysql
  encoding: utf8
  database: pro_jobs_staging
  username: root
  password:
  pool: 5
  
production:
  # Mysql Settings
  encoding: utf8
  adapter: mysql
  database: pro_jobs_production
  username: root
  password:
  pool: 5

cucumber:
  <<: *TEST